[package]
name = "cargo-gui"
version = "0.1.0"
authors = ["eignnx <eignnx@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "1.0.9"
actix-files = "0.1.7"